FROM python:3.9-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /booking

COPY requirements.txt /booking/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /booking/

EXPOSE 8000

CMD ["gunicorn", "web_dev.wsgi:application", "--bind", "0.0.0.0:8000"]
