

services:
  db:
    image: postgres:latest
    container_name: bus_booking_db
    environment:
      POSTGRES_USER: aditya
      POSTGRES_PASSWORD: web_dev_2025
      POSTGRES_DB: aditya
    ports:
      - "5432:5432"
    networks:
      - bus_booking_network
    volumes:
      - db_data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
    container_name: bus_booking
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - bus_booking_network
    environment:
      DATABASE_HOST: db  
      DATABASE_NAME: aditya
      DATABASE_USER: aditya
      DATABASE_PASSWORD: web_dev_2025
    command: gunicorn web_dev.wsgi:application --bind 0.0.0.0:8000

networks:
  bus_booking_network:
    driver: bridge

volumes:
  db_data:
    driver: local

