# Generated by Django 4.2.19 on 2025-02-23 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_seats", models.IntegerField()),
                ("start_location", models.CharField(max_length=100)),
                ("end_location", models.CharField(max_length=100)),
                ("departure_time", models.TimeField()),
                (
                    "duration",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Pilani", "Pilani"),
                            ("Loharu", "Loharu"),
                            ("Delhi", "Delhi"),
                            ("Gurugram", "Gurugram"),
                            ("Rewari", "Rewari"),
                            ("Chandigrah", "Chandigarh"),
                            ("Chirawa", "Chirawa"),
                            ("Ghaziabad", "Ghaziabad"),
                            ("Agra", "Agra"),
                            ("Noida", "Noida"),
                            ("Shikohabad", "Shikohabad"),
                            ("Etawah", "Etawah"),
                            ("Kanour", "Kanpur"),
                            ("Lucknow", "Lucknow"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seatclass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price_class", models.DecimalField(decimal_places=2, max_digits=5)),
                ("available_seats", models.IntegerField()),
                (
                    "bus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_classes",
                        to="bookings.bus",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.day",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intermediatestop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_order", models.IntegerField()),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "fare_multiplier",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intermediate_stops",
                        to="bookings.bus",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.day",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.locations",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bus",
            name="running_days",
            field=models.ManyToManyField(to="bookings.day"),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_tickets", models.IntegerField()),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                ("passenger_name", models.CharField(max_length=100)),
                ("passenger_email", models.EmailField(max_length=100)),
                (
                    "booking_id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=36, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("booked", "Booked"), ("cancelled", "Cancelled")],
                        default="booked",
                        max_length=10,
                    ),
                ),
                ("journey_date", models.DateField(default=django.utils.timezone.now)),
                ("boarding", models.CharField(default="enter", max_length=100)),
                ("deboarding", models.CharField(default="enter", max_length=100)),
                ("time", models.TimeField(default="00:00:00")),
                ("travelling_class", models.CharField(default="none", max_length=100)),
                ("cost", models.IntegerField(default="0")),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bookings.bus"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
