# Generated by Django 4.2.19 on 2025-02-23 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="end_location",
        ),
        migrations.AddField(
            model_name="day",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("1", "Monday"),
                    ("2", "Tuesday"),
                    ("3", "Wednesday"),
                    ("4", "Thursday"),
                    ("5", "Friday"),
                    ("6", "Saturday"),
                    ("7", "Sunday"),
                ],
                default="1",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="intermediatestop",
            name="day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intermediate_stops",
                to="bookings.day",
            ),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_order", models.IntegerField()),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "fare_multiplier",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="bookings.bus",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.day",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.locations",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="intermediatestop",
            name="route",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intermediate_stops_for_route",
                to="bookings.route",
            ),
        ),
    ]
