# Generated by Django 5.1.5 on 2025-02-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "price_multiplier",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("available_seats", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="IntermediateStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("stop_order", models.IntegerField()),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intermediate_stops",
                        to="bookings.bus",
                    ),
                ),
            ],
        ),
    ]
