# Generated by Django 5.1.5 on 2025-02-09 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_seatclass_intermediatestop"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatclass",
            name="bus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seat_classes",
                to="bookings.bus",
            ),
        ),
    ]
