# Generated by Django 4.2.19 on 2025-02-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_remove_route_arrival_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intermediatestop",
            name="bus",
        ),
        migrations.RemoveField(
            model_name="intermediatestop",
            name="day",
        ),
    ]
