# Generated by Django 5.1.5 on 2025-02-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_seatclass_bus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intermediatestop",
            name="stop_name",
        ),
    ]
