# Generated by Django 5.1.5 on 2025-02-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_remove_intermediatestop_stop_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seatclass",
            old_name="price_multiplier",
            new_name="price_class",
        ),
    ]
