# Generated by Django 4.2.19 on 2025-02-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_remove_intermediatestop_bus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="start_location",
        ),
    ]
