# Generated by Django 4.2.19 on 2025-02-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_remove_bus_start_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intermediatestop",
            name="route",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intermediate_stops",
                to="bookings.route",
            ),
        ),
        migrations.RemoveField(
            model_name="route",
            name="day",
        ),
        migrations.AddField(
            model_name="route",
            name="day",
            field=models.ManyToManyField(to="bookings.day"),
        ),
    ]
