# Generated by Django 5.1.5 on 2025-02-09 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_rename_price_multiplier_seatclass_price_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="fare",
        ),
    ]
