# Generated by Django 4.2.19 on 2025-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_intermediatestop_route_remove_route_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Sunday", "Sunday"),
                ],
                default="Monday",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="seatclass",
            name="day",
        ),
        migrations.AddField(
            model_name="seatclass",
            name="day",
            field=models.ManyToManyField(to="bookings.day"),
        ),
    ]
