# Generated by Django 5.1.5 on 2025-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_intermediatestop_fare_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="boarding",
            field=models.CharField(default="enter", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="deboarding",
            field=models.CharField(default="enter", max_length=100),
        ),
    ]
