# Generated by Django 5.1.5 on 2025-02-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_booking_boarding_booking_deboarding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="available_seats",
        ),
    ]
