# Generated by Django 4.2.19 on 2025-02-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_remove_bus_available_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
