# Generated by Django 4.2.19 on 2025-02-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_booking_travelling_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cost",
            field=models.IntegerField(default="0"),
        ),
    ]
